source "https://rubygems.org/"

gem "pg", "~> 0.18"
gem "rake"
gem "sinatra", "~> 1.4"
gem "sinatra-activerecord", "~> 2.0"

group :test do
  gem "capybara"
  gem "database_cleaner"
  gem "factory_girl"
  gem "poltergeist"
  gem "rspec"
end

group :test, :development do
  gem "pry"
end
